### ISSUE TITLE
`Empty` issue in test

### ISSUE THREAD

**Issue by zpz** [zpz/mpservice#90]
in test_streamer.py::test_chain,

```
ERROR    mpservice.streamer:streamer.py:823 exception 'TypeError('can only concatenate str (not "int") to str')' happened for input 'a'
ERROR    mpservice.streamer:streamer.py:823 exception 'ValueError(9)' happened for input '9'
ERROR    mpservice.streamer:streamer.py:745 can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/src/src/mpservice/streamer.py", line 687, in _get_next
    z = self._q.get(timeout=0.1)
  File "/src/src/mpservice/_queues.py", line 515, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/src/mpservice/streamer.py", line 735, in _start_sync
    for x in self._instream:
  File "/src/src/mpservice/streamer.py", line 548, in __next__
    z = self._get_next()
  File "/src/src/mpservice/streamer.py", line 694, in _get_next
    raise self._t.exception()
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/src/src/mpservice/streamer.py", line 675, in _start
    for v in instream:
  File "/src/src/mpservice/streamer.py", line 548, in __next__
    z = self._get_next()
  File "/src/src/mpservice/streamer.py", line 824, in _get_next
    raise e
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/src/tests/test_streamer.py", line 228, in process1
    return x + 2
TypeError: can only concatenate str (not "int") to str
ERROR    mpservice.streamer:streamer.py:823 exception 'ValueError(9)' happened for input '9'
```

**Comment by zpz** [comment]
done
